use_frameworks!

target 'OpenSSLTest_Example' do
  pod 'OpenSSLTest', :path => '../'

  target 'OpenSSLTest_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
